# python
[[plugins]]
repo = 'numirias/semshi'
on_ft = ['python']
hook_source = '''
  UpdateRemotePlugins
'''

# rust 
[[plugins]]
repo = "rust-lang/rust.vim"
on_ft = ['rust']
hook_source = '''
    let g:rustfmt_autosave = 1
'''

# nim
[[plugins]]
repo = "zah/nim.vim"
on_ft = ["nim"]

# c/c++
[[plugins]]
repo = 'jackguo380/vim-lsp-cxx-highlight'
on_ft = ['c', 'cpp']

[[plugins]]
repo = 'vim-jp/vim-cpp'
on_ft = ['c', 'cpp']

# markdown
[[plugins]]
repo = 'iamcco/markdown-preview.nvim'
on_ft = ['markdown', 'pandoc.markdown', 'rmd']
build = 'sh -c "cd app && yarn install"'
