# ヤンクを見やすく
[[plugins]]
repo = 'machakann/vim-highlightedyank'
hook_source = '''
  let g:highlightedyank_highlight_duration = 150
'''

# discord rich presence
[[plugins]]
repo = "andweeb/presence.nvim"
hook_source = '''
  let g:presence_neovim_image_text = "Dark Text Editor"
'''

# コメントアウトを便利にする
[[plugins]]
repo = 'tpope/vim-commentary'

# テキストオブジェクトを囲む
[[plugins]]
repo = 'machakann/vim-sandwich'

# ドキュメントを日本語に
[[plugins]]
repo = 'vim-jp/vimdoc-ja'
