[[plugins]]
repo = 'Shougo/dein.vim'

# [[plugins]]
# repo = 'preservim/nerdtree'
# hook_add = '''
#     let g:webdevicons_enable_nerdtree = 1
# '''

[[plugins]]
repo = 'Shougo/defx.nvim'

[[plugins]]
repo = 'kristijanhusak/defx-icons'

[[plugins]]
repo = 'ryanoasis/vim-devicons'
hook_add = '''
    set encoding=UTF-8
'''

[[plugins]]
repo = 'kristijanhusak/defx-git'

[[plugins]]
repo = "navarasu/onedark.nvim"

# [[plugins]]
# repo = 'prabirshrestha/asyncomplete.vim'
# hook_add = '''
# " TABで補完
# inoremap <expr> <Tab> pumvisible() ? "\<C-n>" : "\<Tab>"
# inoremap <expr> <S-Tab> pumvisible() ? "\<C-p>" : "\<S-Tab>"
# inoremap <expr> <cr> pumvisible() ? "\<C-y>" : "\<cr>"
# 
# let g:asyncomplete_smart_completion = 1
# let g:asyncomplete_auto_popup = 1
# '''
# 
# [[plugins]]
# repo = 'alaviss/nim.nvim'
# on_ft = ['nim', 'nimble']
# hook_add = '''
# au User asyncomplete_setup call asyncomplete#register_source({
#   \ 'name': 'nim',
#   \ 'whitelist': ['nim'],
#   \ 'completor': {opt, ctx -> nim#suggest#sug#GetAllCandidates({start, candidates -> asyncomplete#complete(opt['name'], ctx, start, candidates)})}
#   \ })
# '''

# coc.nvim
[[plugins]]
repo = 'neoclide/coc.nvim'
rev = 'release'
hook_add = '''
  let g:coc_global_extensions = ['coc-json', 'coc-toml', 'coc-pyright', coc-yaml', 'coc-html', 'coc-vimlsp', 'coc-rust-analyzer', 'coc-snippets', 'coc-sh', 'coc-tsserver']
  call coc#util#install()
'''

# コメントアウトを便利にする
[[plugins]]
repo = 'tpope/vim-commentary'

# テキストオブジェクトを囲む
[[plugins]]
repo = 'machakann/vim-sandwich'

# 高性能なターミナル
[[plugins]]
repo = 'kassio/neoterm'
hook_add = '''
  let g:neoterm_autoinsert = 1
  let g:neoterm_autoscroll = 1
  nnoremap <leader>tl :<c-u>exec v:count.'Tclear'<cr>
'''


# [[plugins]]
# repo = 'alaviss/nim.nvim'
# on_ft = ['nim', 'nimble']
# hook_add = '''
# au User asyncomplete_setup call asyncomplete#register_source({
#   \ 'name': 'nim',
#   \ 'whitelist': ['nim'],
#   \ 'completor': {opt, ctx -> nim#suggest#sug#GetAllCandidates({start, candidates -> asyncomplete#complete(opt['name'], ctx, start, candidates)})}
#   \ })
# '''

# semshi - python
[[plugins]]
repo = 'numirias/semshi'
# hook_add = '''
# UpdateRemotePlugins
# '''

# rust.vim 
[[plugins]]
repo = "rust-lang/rust.vim"
hook_add = '''
    let g:rustfmt_autosave = 1
'''

[[plugins]]
repo = 'vim-jp/vim-cpp'

[[plugins]]
repo = 'vim-denops/denops.vim'

[[plugins]]
repo = 'vim-denops/denops-helloworld.vim'


[[plugins]]
repo = 'jackguo380/vim-lsp-cxx-highlight'

[[plugins]]
repo = "zah/nim.vim"

# discord rich presence
[[plugins]]
repo = "andweeb/presence.nvim"
hook_add = '''
let g:presence_neovim_image_text = "Dark Text Editor"
'''

# ドキュメントを日本語に
[[plugins]]
repo = 'vim-jp/vimdoc-ja'

# 翻訳
[[plugins]]
repo = 'skanehira/translate.vim'
hook_add = '''
  nmap <leader>y <Plug>(Translate)
  vmap <leader>y <Plug>(VTranslate)
  nmap <leader>Y <cmd>Translate!<cr>
  vmap <leader>Y <cmd>VTranslate!<cr>
'''

# ヤンクを見やすく
[[plugins]]
repo = 'machakann/vim-highlightedyank'
hook_add = '''
  let g:highlightedyank_highlight_duration = 150
'''

[[plugins]]
repo = 'skanehira/denops-silicon.vim'
